### ISSUE TITLE
Feature request todo list

### ISSUE THREAD

**Issue by laozhu** [laozhu/hugo-nuo#98]
- [ ] Add mobile friendly ToC (#73)
- [ ] Support other comment services (#53, #96)
- [ ] Support MathJax and KaTeX both, switchable (#97 )
- [x] Add PWA support, audited by lighthouse
- [ ] Make a new resume template, printable
- [ ] Add new archives layout for theme (#108)
- [ ] Add multiple images support (#113)

**Comment by laozhu** [comment]
Add PWA support, audited by lighthouse

commit 66defe08fe9b113d102794ce7f3712d33b829595
